services:
  - type: web
    plan: free
    region: frankfurt
    name: json_viewer
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn json_viewer.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4